# Generated by Django 3.1.3 on 2023-05-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_incorrect',
            field=models.BooleanField(choices=[(True, 'Incorrect'), (False, 'Correct')], default=False),
        ),
    ]
